image: node:latest

build-client:
  stage: build
  before_script:
    - yarn install
  script:
    - yarn run build

lint-client:
  stage: test
  before_script:
    - yarn install
  script:
    - yarn run lint
# no unit test yet
# test-client:
#  stage: test
#  before_script:
#    - yarn install
#  script:
#    - yarn run test
