#!/bin/bash
set -e

echo "Pull modifications"

git fetch && git reset --hard @{u}

echo "Check for dependencies..."

npm i

echo "Deploying on the server..."

pm2 restart Trotter_Client

echo "Application deployed successfully!"
